server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Khai báo chuẩn MIME types để trình duyệt nhận diện đúng tệp ảnh/3D
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Bật nén Gzip để tải file JS/Textures siêu nhanh
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;

    # Cấu hình Single Page Application (Bỏ qua lỗi 404 khi F5)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cấu hình riêng cho tài nguyên Tĩnh (Ảnh Textures, JS, CSS, Media)
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        add_header Access-Control-Allow-Origin "*";
        try_files $uri =404;
    }

    # Sửa lỗi 500/404 khi Shift + F5
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}